INSTRUMENTS_COLLECTION_PREFIX = 'instrument'
INSTRUMENTS_COLLECTION_TYPE = 'v'
INSTRUMENTS_COLLECTION_SCORE = 0
INSTRUMENTS_PARENT_NAME = 'Instruments'

INSTRUMENTS_OUTPUTFORMAT = 'hbins'

INSTRUMENTS_SORTING_OPTIONS = [
    'name',
]
